apiVersion: v1
kind: ConfigMap
metadata:
  name: iris-api-config
  namespace: mlops
data:
  BACKEND_STORE_URI: postgresql://mlflow:Mlops@2026@34.45.83.138:5432/mlflowdb
  ARTIFACT_ROOT: gs://mlops-platform-artifacts-dev
