apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- secretproviderclass.yaml
- configmap.yaml
- deployment.yaml
- service.yaml

images:
- name: mlflow
  newName: us-central1-docker.pkg.dev/project-cd87c2b0-43f1-4451-809/mlops-repo/mlflow
  newTag: v3
