apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mlflow-secrets
  namespace: mlflow

spec:
  provider: gcp

  parameters:
    secrets: |
      - resourceName: "projects/983022077725/secrets/mlflow-db-password/versions/latest"
        path: "db-password"

      - resourceName: "projects/983022077725/secrets/mlflow-db-user/versions/latest"
        path: "db-user"

      - resourceName: "projects/983022077725/secrets/mlflow-db-name/versions/latest"
        path: "db-name"

  secretObjects:
    - secretName: mlflow-secret
      type: Opaque
      data:
        - objectName: db-password
          key: DB_PASSWORD

        - objectName: db-user
          key: DB_USER

        - objectName: db-name
          key: DB_NAME
